/**
 * FALLBACK DATA — used when Gemini API is unavailable during demo.
 * Realistic enough to show judges all features working.
 */

import { DiagnosisResult } from './types'

export const FALLBACK_DIAGNOSIS: DiagnosisResult = {
  type: 'Overwhelmed',
  score: 72,
  description:
    'Patient presents with task-paralysis symptoms: multiple active deadlines causing decision fatigue. Unable to identify a clear starting point, leading to avoidance behaviour.',
  symptoms: [
    'Stares at task list without starting',
    'Switches between tasks without completing any',
    'Underestimates time needed for each item',
  ],
  prescription: [
    'Start with the smallest task (< 10 min) to build momentum',
    'Set a 25-min timer — work on ONE thing only',
    'Use Micro Plan to break each task before touching it',
  ],
  emoji: '😰',
}

export const FALLBACK_GHOST = (taskTitle: string) => `
DRAFT — Auto-generated by DeadlineDoctor Ghost Mode
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Subject: Submission – ${taskTitle}

Dear [RECIPIENT NAME],

Please find attached my submission for ${taskTitle}.

I have completed all required sections as outlined in the brief. Key highlights include:

• Section 1: [YOUR MAIN POINT]
• Section 2: [SUPPORTING DETAIL]
• Section 3: [CONCLUSION / NEXT STEPS]

Please let me know if you need any additional information or clarification.

Regards,
[YOUR NAME]
[YOUR CONTACT]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚡ Generated by DeadlineDoctor · Review before sending
`.trim()

export const FALLBACK_NEGOTIATE = (taskTitle: string) => ({
  subject: `Request for Extension – ${taskTitle}`,
  email: `Dear [RECIPIENT NAME],

I hope this message finds you well. I am writing to respectfully request a brief extension for ${taskTitle}, originally due on [ORIGINAL DATE].

I have made significant progress on this work; however, due to [BRIEF REASON — e.g. overlapping commitments / unexpected circumstances], I require an additional 48 hours to ensure the quality meets the expected standard.

I would be grateful if the new deadline could be set to [NEW DATE]. I take full responsibility for this request and assure you this will not affect the quality of the final deliverable.

Thank you sincerely for your understanding.

Kind regards,
[YOUR NAME]`,
  tone: 'professional',
})

export const FALLBACK_SCHEDULE = [
  { id: 'mt1', label: 'Read the task brief and highlight key requirements', duration: 10, done: false },
  { id: 'mt2', label: 'Create a rough outline or structure', duration: 15, done: false },
  { id: 'mt3', label: 'Complete the first section (just a draft, not perfect)', duration: 20, done: false },
  { id: 'mt4', label: 'Complete remaining sections', duration: 25, done: false },
  { id: 'mt5', label: 'Review, polish, and submit', duration: 10, done: false },
]
